version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependências..."
      - pip install checkov

  pre_build:
    commands:
      - echo "Baixando políticas personalizadas do S3..."
      - aws s3 cp s3://checkov-policy-store . --region us-east-1

  build:
    commands:
      - echo "Rodando análise de segurança com Checkov..."
      - checkov -d . --config-file .checkov.yml || true