name: Terraform Security Check with Checkov

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    name: Run Checkov Security Scan

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar o Checkov
        run: pip install checkov

      - name: Rodar análise de segurança
        run: checkov -d . --quiet
