name: Terraform Security Check with Checkov

# Dispara o workflow em todo push para a branch 'main'
on:
  push:
    branches: [ main ]

permissions:
  contents: read # Apenas leitura do repositório

jobs:
  checkov-scan:
    # Nome do Job
    name: Run Checkov Security Scan
    
    # Diz ao GitHub Actions para usar seu projeto CodeBuild como a máquina (runner)
    runs-on: codebuild-checkov-validate-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Dependências (Checkov e JQ)
        run: |
          pip install checkov
          # O 'jq' é necessário para ler a resposta JSON do assume-role
          # A imagem do CodeBuild é baseada em Ubuntu, então usamos apt-get
          yum install -y jq

      - name: Assumir Role da conta PRD e exportar credenciais
        run: |
          echo "Assumindo a role da conta PRD..."
          # 1. Pede o "crachá de visitante" (Assume Role)
          CREDS=$(aws sts assume-role \
                    --role-arn "arn:aws:iam::977919013454:role/clouddog-checkov-prd-role" \
                    --role-session-name "CheckovGitHubActionSession")
          
          # 2. Configura o AWS CLI para USAR esse crachá nos próximos passos
          #    Usamos $GITHUB_ENV para passar as variáveis entre os 'steps'
          echo "AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r .Credentials.AccessKeyId)" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r .Credentials.SecretAccessKey)" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo $CREDS | jq -r .Credentials.SessionToken)" >> $GITHUB_ENV
          echo "Credenciais temporárias prontas para os próximos passos."
      
      - name: Baixar arquivo de configuração do S3 (de PRD)
        run: |
          echo "Baixando arquivo checkov.yml da pasta /checkov/ do bucket S3 de PRD..."
          mkdir -p ./checkov_policies
          
          # Executa o comando de download
          aws s3 cp s3://clouddog-checkov-prd-bucket/checkov/checkov.yml ./checkov_policies/checkov.yml
          
          # --- DEBUG ADICIONADO ABAIXO ---
          echo "Verificando o conteúdo da pasta checkov_policies:"
          ls -la ./checkov_policies
          
          echo "Verificando o caminho completo do workspace:"
          echo ${{ github.workspace }}
          
          echo "Verificando se o arquivo existe no caminho esperado:"
          if [ -f "${{ github.workspace }}/checkov_policies/checkov.yml" ]; then
            echo "SUCESSO: Arquivo checkov.yml encontrado!"
          else
            echo "ERRO: Arquivo checkov.yml NÃO encontrado no caminho esperado!"
            exit 1 # Falha o build aqui se o arquivo não foi baixado
          fi
          # --- DEBUG ADICIONADO ACIMA ---
          
          echo "Arquivo de configuração baixado."

      # ... (o step "Rodar análise de segurança" continua o mesmo) ...
      - name: Rodar análise de segurança
        run: |
          echo "Rodando scan do Checkov na pasta ./terraform usando a CONFIGURAÇÃO do S3..."
          checkov -d ./terraform --config-file ${{ github.workspace }}/checkov_policies/checkov.yml --skip-check CKV_AWS_19,CKV2_AWS_62,CKV2_AWS_6,CKV_AWS_144,CKV_AWS_21,CKV_AWS_145,CKV2_AWS_61,CKV_AWS_18,CKV_AWS_20,CKV2_AWS_6
